site_name: Cosmere RPG campaign wiki
theme:
  name: terminal
  palette: gruvbox_dark
  features: 
    #- navigation.side.hide
    - navigation.top.hide

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Home: index.md 
  - The World: The-World.md
  - Notable NPCs: notable-npcs.md
  - Session logs:
    - Session 1: session-001.md

