site_name: Cosmere RPG campaign wiki
theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle: 
        icon: material/weather-night
        name: Switch to light mode


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Rules: rules/cheatsheet.md
  - Session notes: campaign/session-notes.md
  - Quests:
    - Active Quests: quests/active-quests.md
    - Completed Quests: quests/completed-quests.md
    - Failed Quests: quests/failed-quests.md
  - Locations:
    - World: locations/world-map.md
    - Purelake: locations/purelake.md
    - Jah Keved: locations/jah-keved.md
  - NPCs:
    - Allies: NPCs/allies.md
    - Villains: NPCs/villains.md
    - Other: NPCs/other.md
  - Factions:
    - Obitelj Ramavel: factions/obitelj-Ramavel.md
    - Jah Keved Highprinces: factions/jah-keved-highprinces.md
  - Characters:
    - Party Overview: characters/party-overview.md
    - Backstories: characters/backstories.md
  - Items: items/items.md

