site_name: Cosmere RPG campaign wiki
theme:
  name: terminal
  palette: gruvbox_dark
  features: 
    #- navigation.side.hide
    - navigation.top.hide

markdown_extensions:
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  - Campaign:
    - Overview: campaign/overview.md
    - Timeline: campaign/timeline.md
  - Quests:
    - Active Quests: quests/active-quests.md
    - Completed Quests: quests/completed-quests.md
    - Failed Quests: quests/failed-quests.md
  - Locations:
    - World Map: locations/world-map.md
    - Jah Keved: locations/jah-keved.md
  - NPCs:
    - Allies: NPCs/allies.md
    - Villains: NPCs/villains.md
    - Other: NPCs/other.md

  

